Repository Sarvenaz83/HarryPotterAPI, pull requests merged in 2024-01, with the labels that each got.

#14 Feature/create author command new
  .gitignore
  API/Controllers/AuthorController.cs
  Application/Commands/AuthorCommands/CreateAuthor/CreateAuthorCommand.cs
  Application/Commands/AuthorCommands/CreateAuthor/CreateAuthorCommandHandler.cs
  Infrastructure/Migrations/20240115215351_NewNameForAuthors1.Designer.cs
  Infrastructure/Migrations/20240115215351_NewNameForAuthors1.cs
  Infrastructure/Migrations/HarryPotterContextModelSnapshot.cs
  Tests/AuthorTests/CommandTests/AuthorCommandsTests/CreateAuthorCommnadHandlerTest.cs
  Tests/AuthorTests/QueriesTest/AuthorQueries/GetAllAuthorsQueryHandlerTest.cs
Labels: Task

#31 Done with DeleteBookCommand + Handler, BookController(DeleteBook) and…
  API/Controllers/BookController.cs
  Application/Commands/BookCommands/DeleteBook/DeleteBookCommand.cs
  Application/Commands/BookCommands/DeleteBook/DeleteBookCommandHandler.cs
  Tests/BookTests/CommandTests/DeleteBookCommandHandlerTests.cs
Labels: Task

#49 Feature/skapa updatebook command
  API/Controllers/BookController.cs
  Application/Commands/BookCommands/UpdateBook/UpdateBookByIdCommand.cs
  Application/Commands/BookCommands/UpdateBook/UpdateBookByIdCommandHandler.cs
  Application/Queries/BookQueries/GetBookById/GetBookByIdQuery.cs
  Application/Queries/BookQueries/GetBookById/GetBookByIdQueryHandler.cs
  Infrastructure/Repository/BookRepository/BookRepository.cs
  Infrastructure/Repository/BookRepository/IBookRepository.cs
  Tests/BookTests/CommandTests/UpdateBookByIdCommandHandlerTests.cs
Labels: Task

#55 Feature/delete author
  API/Controllers/AuthorController.cs
  Application/Commands/AuthorCommands/DeleteAuthor/DeleteAuthorByIdCommand.cs
  Application/Commands/AuthorCommands/DeleteAuthor/DeleteAuthorByIdCommandHandler.cs
  Infrastructure/Repository/AuthorRepository/AuthorRepository.cs
  Tests/AuthorTests/CommandTests/AuthorCommandsTests/DeleteAuthorByIdCommandHandlerTest.cs
Labels: Task

#78 Get book by author name implemented
  API/Controllers/BookController.cs
  Application/Queries/BookQueries/GetBookByAuthorName/GetBookByAuthorNameQuery.cs
  Application/Queries/BookQueries/GetBookByAuthorName/GetBookByAuthorNameQueryHandler.cs
  Infrastructure/Repository/BookRepository/BookRepository.cs
  Infrastructure/Repository/BookRepository/IBookRepository.cs
  Tests/BookTests/QueryTests/GetBookByAuthorNameQueryHandlerTests.cs
Labels: Feature

#79 Den delen kommer att lägga till Get books by rating in book contorlle…
  API/Controllers/BookController.cs
  Application/Queries/BookQueries/GetBooksByRating/GetBooksByRatingQuery.cs
  Application/Queries/BookQueries/GetBooksByRating/GetBooksByRatingQueryHandler.cs
  Infrastructure/Repository/BookRepository/BookRepository.cs
  Infrastructure/Repository/BookRepository/IBookRepository.cs
  Tests/BookTests/QueryTests/GetBooksByRatingQueryHandlerTest.cs
Labels: Task

#105 Done with GetAllPurchaseDetail
  API/Controllers/PurchaseController.cs
  API/Controllers/UserController.cs
  Application/Commands/UserCommands/DeleteUser/DeleteUserByIdCommand.cs
  Application/Commands/UserCommands/DeleteUser/DeleteUserByIdCommandHandler.cs
  Application/Commands/UserCommands/RegisterUser/RegisterUserCommand.cs
  Application/Commands/UserCommands/RegisterUser/RegisterUserCommandHandler.cs
  Application/Dtos/AuthorDto.cs
  Application/Queries/PurchaseDetailsQuery/GetAllPurchaseDetail/GetAllPurchaseDetailQuery.cs
  Application/Queries/PurchaseDetailsQuery/GetAllPurchaseDetail/GetAllPurchaseDetailQueryHandler.cs
  Application/Queries/UserQueries/LoginUserQuery.cs
  Application/Queries/UserQueries/LoginUserQueryHandler.cs
  Application/Validators/PurchaseDetailValidator.cs
  Application/Validators/UserValidator.cs
  Infrastructure/DependencyInjection.cs
  Infrastructure/Migrations/20240123182951_MigrationUpdateUser.cs
  Infrastructure/Repository/PurchaseRepository/IPurchaseRepository.cs
  Infrastructure/Repository/PurchaseRepository/PurchaseRepository.cs
  Infrastructure/Repository/WalletRepository/WalletRepository.cs
  Tests/BookTests/CommandTests/DeleteBookCommandHandlerTests.cs
  Tests/BookTests/CommandTests/UpdateBookByIdCommandHandlerTests.cs
  Tests/PurchaseDetailTests/QueriesTests/GetAllPurchaseDetailQueryHandlerTests.cs
  Tests/UserTests/LoginUserQueryHandlerTest.cs
  Tests/UserTests/RegisterUserCommandHandlerTest.cs
  Tests/UserTests/UserQueries/GetAllUsersQueryHandlerTest.cs
Labels: documentation, Feature, Task

#106 Feature/skapa getallpurchasehistoriesquery
  API/Controllers/UserController.cs
  Application/Application.csproj
  Application/Queries/PurchaseHistoriesQueries/GetAllPurchaseHistoriesQuery.cs
  Application/Queries/PurchaseHistoriesQueries/GetAllPurchaseHistoriesQueryHandler.cs
  Application/Validators/PurchaseHistoriesValidator.cs
  Domain/Models/PurchaseHistory.cs
  Infrastructure/DataSeeder.cs
  Infrastructure/DatabaseContext/HarryPotterContext.cs
  Infrastructure/DependencyInjection.cs
  Infrastructure/Infrastructure.csproj
  Infrastructure/Migrations/20240126110358_nymigration.Designer.cs
  Infrastructure/Migrations/20240126110358_nymigration.cs
  Infrastructure/Migrations/HarryPotterContextModelSnapshot.cs
  Infrastructure/Repository/PurchaseHistoriesRepository/IPurchaseHistoriesRepository.cs
  Infrastructure/Repository/PurchaseHistoriesRepository/PurchaseHistoriesRepository.cs
Labels: Feature, Task

#107 Feature/get book by title
  API/Controllers/BookController.cs
  Application/Queries/BookQueries/GetBookByTitle/GetBookByTitleQuery.cs
  Application/Queries/BookQueries/GetBookByTitle/GetBookByTitleQueryHandler.cs
  Infrastructure/Repository/BookRepository/BookRepository.cs
  Infrastructure/Repository/BookRepository/IBookRepository.cs
  Tests/BookTests/QueryTests/GetBookByTitleQueryHandlerTests.cs
Labels: Feature, Task
